apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    env: production
    country: India
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
      country: India
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        env: production
        country: India
    spec:
      containers:
      - image: yash6899/httpd-centos:3
        name: myapp
        ports:
          - nodePort: 31000
             port: 80
             targetPort: 80
          name: myapp
        volumeMounts:
        - name: webapp-persistent-storage
          mountPath: /var/log/httpd
      volumes:
      - name: webapp-persistent-storage
        persistentVolumeClaim:
          claimName: webapp-pv-claim
