apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pv-claim
  labels:
    env: production
    country: India
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi