apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    env: production
    country: India
spec:
  selector:
    env: production
    country: India
  type:NodePort
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 80