apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    env: production
    country: India
spec:
  selector:
    env: production
    country: India
  type: NodePort
  ports:
    - nodePort: 30022
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      env: production
      country: India
  template:
    metadata:
      labels:
        env: production
        country: India
    spec:
      containers:
      - image: yash6899/httpd-centos:1
        name: myapp
        ports:
          - containerPort: 80
        volumeMounts:
        - name: webapp-persistent-storage
          mountPath: www/var/log/
      volumes:
      - name: webapp-persistent-storage
        persistentVolumeClaim:
          claimName: webapp-pv-claim
